### ISSUE TITLE
Full example for summarization

### ISSUE THREAD

**Issue by sersoage** [gao-g/prelude#1]
Hi, great work! would it be possible to add a full working example for summarization?

**Comment by dkmisra** [comment]
You mean you want the original context, the agent's response, and the edits performed by the user?

cc' @gao-g and @ataymano

**Comment by sersoage** [comment]
Yes, or some example where it is learning from the feedback.

**Comment by dkmisra** [comment]
We certainly have those logs. Let me see if it is okay to share one or two examples and we will get back. The main concern is that we don't own the data and we don't want to re-release it but perhaps 1-2 examples is fair use.

**Comment by sersoage** [comment]
Thank you!!

**Comment by ataymano** [comment]
Hi,
please find couple of examples of input context, completion proposed by the agent, summary edited by user, user preference inferred by the agent and ground truth user preference from the CIPHER.1.Bert experiment:


|context|completion|edited|inferred preference|groundtruth preference|
|-|-|-|-|-|
|Aphex Twin (born Richard David James, 18 August 1971, in Limerick, Ireland) is an Irish-born Cornish musician. He lives and works in the UK. He is a famous electronic musician.  Aphex Twin is not his real name. His real name is Richard David James. His name is a combination of Aphex Systems Limited, a brand of audio signal processing equipment and the word Twin to remember his brother. His brother was stillborn, but given the name Richard James.  Early life  Aphex Twin was born in Limerick, Ireland. He grew up in Cornwall, U.K. He started to make music when he was a teenager. In 1991, he formed a record label called Rephlex Records.  After he became well known, he moved to London. This was so he could be in a place that was closer to other people. He however returned to Cornwall a few years later after meeting his wife. He still makes a lot of music today and uses many different pseudonyms (names). He lives in an old bank. He has bought interesting things like a tank and a submarine.  Selected works  Albums  Selected Ambient Works 85-92 (1992)  Selected Ambient Works Volume II (1994)  ...I Care Because You Do (1995)  Richard D. James Album (1996)  Drukqs (2001)  Syro (2014)  EPs and Singles  Digeridoo (1992)  Xylem Tube EP (1992)  On/On Remixes (1993)  Ventolin/Ventolin Remixes EP (1995)  Donkey Rhubarb (1995)  Girl/Boy EP (1996)  Come to Daddy EP (1997)  Windowlicker (1999)  Analord 10 in the Analord Series (2004)  Computer Controlled Acoustic Instruments (2015)  Promotions and Compilations  Words & Music (1994) (Interview and tracks from Selected Ambient Works Volume II)  Classics (1994) (Many early singles, rare and live tracks)  51/13 Singles Collection (1996) (Australia-only release)  Cock 10/54 Cymru Beats (drukqs promo)  26 Mixes for Cash (2003), a lot of music remade for other artists (and four original songs)  2 Mixes on a 12" for Cash (2003), a 26 Mixes promo  Falling Free, Curve Remix (2005), a 26 Mixes LP  Discography using other names  AFX  Analogue Bubblebath (1991)  Analogue Bubblebath 2 (1992)  Analogue Bubblebath 3 (1993)  Analogue Bubblebath 4 (1994)  Analogue Bubblebath 5 (1995 unreleased)  Analogue Bubblebath 3.1 (1997)  Hangable Auto Bulb (1995, re-released 2005)  Hangable Auto Bulb 2 (1995, re-released 2005)  2 Remixes By AFX (2001)  Smojphace EP (2003)  "Mangle 11 (Circuit Bent V.I.P. Mix)" (this is on the Rephlexions album that was worked on by many people (2003))  Analord (EP series, mostly as AFX) (2005)  AFX/LFO (split 12" between AFX/LFO) (2005)   Bradley Strider  Bradley's Beat (1991)/(1995 re-issue)  Bradley's Robot (1993)  Caustic Window  Joyrex J4 (1992)  Joyrex J5 (1992)  Joyrex J9 (1993)  CAT 023 (unreleased, only 4 copies pressed)  Caustic Window Compilation (1998)  Gak  GAK (1994)  Martin Tressider  In the Universal Indicator series:  Universal Indicator: Red (1989)  Universal Indicator: Green (1995)  Polygon Window  (Surfing on Sine Waves) (1993, re-released 2001)  (Quoth) (1993)  Power Pill  Pac-Man (1992)  Q-Chastic  Q-Chastic EP (1992 unreleased)  Universal Indicator  Universal Indicator: Blue (1992)  Universal Indicator: Yellow (1993)  References  Other websites   Rephlex Records. This is Aphex Twin's record label.  1971 births Living people Aphex Twin|Aphex Twin, whose real name is Richard David James, was born on August 18, 1971, in Limerick, Ireland, and is a renowned electronic musician based in the UK. He adopted his stage name from Aphex Systems Limited, an audio equipment brand, and "Twin" in memory of his stillborn brother, who was also named Richard James.  Raised in Cornwall, UK, Aphex Twin began making music as a teenager and founded Rephlex Records in 1991. He moved to London to be closer to the music scene but later returned to Cornwall after marrying. He is known for his eclectic purchases, including a tank and a submarine, and he resides in a former bank.  Aphex Twin has released several influential albums, including "Selected Ambient Works 85-92" and "Syro," as well as numerous EPs and singles like "Digeridoo" and "Windowlicker." He has also compiled and promoted his work through collections such as "Classics" and "26 Mixes for Cash."  Under various pseudonyms, Aphex Twin has an extensive discography, including works as AFX, Bradley Strider, Caustic Window, and Polygon Window, among others. He has contributed to the Universal Indicator series and released music under other monikers, showcasing his versatility as an artist.  Aphex Twin continues to be an influential figure in electronic music and is associated with his record label, Rephlex Records. He is recognized as a living artist born in 1971.|- Born: Richard David James, August 18, 1971, Limerick, Ireland - Stage Name: Aphex Twin, from "Aphex Systems Limited" + tribute to stillborn twin brother - Raised: Cornwall, UK - Early Music Career: Started as a teenager - Record Label: Founded Rephlex Records, 1991 - Relocation: Moved to London, returned to Cornwall post-marriage - Notable Purchases: Tank, submarine; lives in a former bank - Key Albums: "Selected Ambient Works 85-92," "Syro" - Notable EPs/Singles: "Digeridoo," "Windowlicker" - Collections: "Classics," "26 Mixes for Cash" - Pseudonyms: AFX, Bradley Strider, Caustic Window, Polygon Window - Other Projects: Universal Indicator series - Influence: Prominent figure in electronic music - Association: Rephlex Records - Status: Active artist, born in 1971| |bullet points, parallel structure, brief|
|...|...|...|...|...|
|Mario Cashmere Manningham (born May 25, 1986) is an American football wide receiver who currently plays for the San Francisco 49ers of the National Football League. He was drafted by the New York Giants in the third round of the 2008 NFL Draft. He played college football at Michigan.  College career  In 2005, as a freshman, Manningham had 27 receptions for 433 yards and six touchdowns, including the game-winning catch as time expired in the game against Penn State, handing the Lions their only loss that season.  Manningham finished 2006 with a total 38 receptions 703 yards and nine touchdowns. He was named Big Ten Offensive Player of the Week two weeks in a row, first against Notre Dame and then against Wisconsin.  Manningham had a total of 72 receptions for 1,174 yards and 12 touchdowns in 2007.  After the 2007 season, Manningham opted to forgo (forget, not do) his eligibility for his senior year in 2008 and entered the NFL Draft. He finished his career at Michigan with 137 receptions for 2,310 yards and 27 touchdowns.  Those marks (in order) placed him ninth, fifth, and fourth in school history.  Professional career  New York Giants Manningham was selected in the third round (95th overall) of the 2008 NFL Draft by the New York Giants.  2008 season During rookie training camp, Manningham said that he looked forward to playing with fellow former Michigan Wolverine Amani Toomer, who was with New York at the time. Manningham signed a four-year deal worth up to $2.3 million as a rookie.  2009 season Manningham has been working on his punt return abilities and competed for the punt returner spot in 2009.  Manningham kicked off the 2009 NFL season by catching three passes for 58 yards and a touchdown en route to the Giants' 23-17 win over the Washington Redskins. He followed this up by catching 10 passes for 150 yards and a juggling sliding catch for a touchdown in the Giants' 33-31 win over the Dallas Cowboys.  Manningham became the starting wide receiver opposite Steve Smith after fellow receiver Domenik Hixon was injured in a Week 2 game against the Dallas Cowboys.  2011 season Manningham let Victor Cruz and Hakeem Nicks take much of his playing time, and Manningham was only the #3 wideout in 2011.  On February 5, 2012, Manningham made a catch in the fourth quarter of Superbowl XLVI to set up the win against the Patriots.  Trailing by 2 points with 3 minutes 46 seconds remaining, the Giants started the winning drive.  Eli Manning lofted a long pass down the left sideline to Mario Manningham, who kept his feet inbounds by inches with two defenders around him. The Giants went on to beat the New England Patriots 21-17. Manningham ended the game with 5 catches for 73 yards. Most people think that he will not return to the Giants.  Legal issues  Manningham  had reportedly been removed from "multiple teams'" draft boards due to alleged marijuana use in college. Mario denied testing positive at first, then sent a letter to all 32 teams saying he lied. Manningham claimed he failed two drug tests. Bob McGinn of the Milwaukee Journal-Sentinel reported that Manningham scored a 6 out of 50 on the Wonderlic exam. This along with several other problems caused his draft value to drop.  References   "Mario Manningham: His best and worst moments".   "Manningham Big Ten Player of the Week - Again ".  "Manningham faces surgery".  "Michigan survives Ball State scare to keep perfect season alive". ESPN. Associated Press. Retrieved 2011-09-24.   "ESPN Profile: Mario Manningham".  "Giants select talented but troubled WR Mario Manningham in third round".  1986 births Living people American football wide receivers New York Giants players San Francisco 49ers players Sportspeople from Ohio|- **Birth and Early Career:**   - Born: May 25, 1986   - College: University of Michigan  - **College Career Highlights:**   - 2005: 27 receptions, 433 yards, 6 TDs; game-winning catch against Penn State   - 2006: 38 receptions, 703 yards, 9 TDs; Big Ten Offensive Player of the Week twice   - 2007: 72 receptions, 1,174 yards, 12 TDs   - Career at Michigan: 137 receptions, 2,310 yards, 27 TDs; ranks 9th, 5th, and 4th in school history   - Declared for NFL Draft after junior year  - **Professional Career:**   - Drafted: 2008, 3rd round (95th overall) by New York Giants   - 2008 Season: Signed four-year deal, looked forward to playing with Amani Toomer   - 2009 Season: Competed as punt returner, became starting WR, notable performances against Redskins and Cowboys   - 2011 Season: Played as #3 wideout behind Victor Cruz and Hakeem Nicks  - **Super Bowl XLVI:**   - February 5, 2012: Key catch in fourth quarter to set up Giants' victory over Patriots, 5 catches for 73 yards in the game  - **Legal Issues:**   - Alleged marijuana use in college, admitted to failing two drug tests   - Scored 6 out of 50 on Wonderlic exam   - Draft value affected by these issues  - **Categories:**   - 1986 births   - Living people   - American football wide receivers   - New York Giants players   - San Francisco 49ers players   - Sportspeople from Ohio|- **Birth and Early Career:**   - Born: May 25, 1986   - College: University of Michigan  - **College Career Highlights:**   - 2005: 27 receptions, 433 yards, 6 TDs; game-winning catch against Penn State   - 2006: 38 receptions, 703 yards, 9 TDs; Big Ten Offensive Player of the Week twice   - 2007: 72 receptions, 1,174 yards, 12 TDs   - Career at Michigan: 137 receptions, 2,310 yards, 27 TDs; ranks 9th, 5th, and 4th in school history   - Declared for NFL Draft after junior year  - **Professional Career:**   - Drafted: 2008, 3rd round (95th overall) by New York Giants   - 2008 Season: Signed four-year deal, looked forward to playing with Amani Toomer   - 2009 Season: Competed as punt returner, became starting WR, notable performances against Redskins and Cowboys   - 2011 Season: Played as #3 wideout behind Victor Cruz and Hakeem Nicks  - **Super Bowl XLVI:**   - February 5, 2012: Key catch in fourth quarter to set up Giants' victory over Patriots, 5 catches for 73 yards in the game  - **Legal Issues:**   - Alleged marijuana use in college, admitted to failing two drug tests   - Scored 6 out of 50 on Wonderlic exam   - Draft value affected by these issues  - **Categories:**   - 1986 births   - Living people   - American football wide receivers   - New York Giants players   - San Francisco 49ers players   - Sportspeople from Ohio|Concise bullet points, factual emphasis, chronological structure.|bullet points, parallel structure, brief|
|...|...|...|...|...|

**Comment by dkmisra** [comment]
I am resolving this issue. Feel free to open if more details are needed.
